language: go
sudo: false
before_install:
- go get github.com/mitchellh/gox
install:
- #skip
script:
- go get -t -v ./...
- diff -u <(echo -n) <(gofmt -d .)
- go test -v -race ./...
- gox -os="linux darwin windows" -arch="amd64" -output="bin/ecs-deploy_{{.OS}}_{{.Arch}}"
  -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hU6SQYTY76ul0B6CmM7TvYdZ/+OSVwgWb036xSgM1FOGri1Xg0IzbAigAcTmJDY2ZEoFpx5ggYyn95uV5IsrmJnOPTQKTcf8pSaaSVHhyJdZiwz94Ji9vzGiFFWoTUnPk39FIuwXur6faUe/vHUEW/95gZA6R5VZGDd8LSiNL7mJhn/fby+GvzCERk9lw5+UDV0i+Ia3f4jmWzdtCM1C6rIicp397kM6z7G4LarUhvnSLC/76U5B2/xHzHxOBRIOgw6tl6fOmjbNVhMEu/rGLpaJCaNTZ8eRwaCkEgIFBbI+X6JxDQak2rxRJWHwFpJTOEnWL0tB3CvLhzlC0/V+mnWhWlvZg6zM2Nt3UVerfUwr6AXUCjFwD/Q1Ao4aKRko0dzN5QAqto6DN7SKI8hB07vCwqocMNBbF4cN0+24vhottUDGGru9fdcC8ZeocpUXA7OeI8tR0c0Au8F8vC8YuhuUmlspwUrO/+6aRcF94oyluW6LXD7IMBF3IptNjJni+Ojs50c/gtaIVJPr8nL59AN81NKEctaH14QhMZ6dFMJ12EFoFnXinaaY6wfZb47mzQNqF9zfphduVGgixIRmBH6MMkX942e/qYYcxaXi27Wj9ZMWTrpH0kwGlh0c6DjR18leBs0+M/qv7Cg0BfMh2eV8wsbviU8BB0Y6qJx0/vo=
  file: 
    - "bin/ecs-deploy_windows_amd64.exe"
    - "bin/ecs-deploy_linux_amd64"
    - "bin/ecs-deploy_darwin_amd64"
  on:
    repo: enderv/ecs-deploy
    tags: true